[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2021"

[dependencies]
csv = "1.3"
indicatif = "0.17"
comfy-table = "7.1"
regex = "1.10"
rusqlite = { version = "0.32", features = ["functions"] }
rustyline = "14"
clap = { version = "4.5.11", features = ["derive"] }
dirs = "5.0"
