[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.3"
indicatif = "0.17"
lazy_static = "1.4"
comfy-table = "7.1"
regex = "1.10"
rusqlite = { version = "0.30", features = ["functions"] }
rustyline = "13"
clap = { version = "4.4.15", features = ["derive"] }
dirs = "5.0"
