[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
indicatif = "0.16"
lazy_static = "1.4"
comfy-table = "4.1"
regex = "1.5"
rusqlite = { version = "0.25", features = ["functions"] }
rustyline = "8.2"
clap = "3.0.0-beta.2"
dirs = "3.0"
