[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "*"
indicatif = "*"
lazy_static = "*"
comfy-table = "1.3"
regex = "*"
rusqlite = "*"
rustyline = "*"
clap = "3.0.0-beta.2"