[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
indicatif = "0.16"
lazy_static = "1.4"
comfy-table = "6.1"
regex = "1.7"
rusqlite = { version = "0.28", features = ["functions"] }
rustyline = "10.0"
clap = { version = "4.0.26", features = ["derive"] }
dirs = "4.0"
