[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
indicatif = "0.15"
lazy_static = "1.4"
comfy-table = "1.3"
regex = "1.4"
rusqlite = "0.24"
rustyline = "6.3"
clap = "3.0.0-beta.2"
