[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.2"
indicatif = "0.17"
lazy_static = "1.4"
comfy-table = "7.0"
regex = "1.9"
rusqlite = { version = "0.29", features = ["functions"] }
rustyline = "10.1"
clap = { version = "4.3.22", features = ["derive"] }
dirs = "5.0"
