[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.2"
indicatif = "0.17"
lazy_static = "1.4"
comfy-table = "6.1"
regex = "1.7"
rusqlite = { version = "0.29", features = ["functions"] }
rustyline = "11.0"
clap = { version = "4.1.11", features = ["derive"] }
dirs = "5.0"
