[package]
name = "csvsql"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
indicatif = "0.16"
lazy_static = "1.4"
comfy-table = "6.0"
regex = "1.5"
rusqlite = { version = "0.27", features = ["functions"] }
rustyline = "9.1"
clap = { version = "3.2.3", features = ["derive"] }
dirs = "4.0"
